@startuml
'https://plantuml.com/sequence-diagram
actor Client
participant WebsiteHomePage
participant DynamoDBGetSimilarUsersActivity
database UsersTable
autonumber

Client -> WebsiteHomePage:
WebsiteHomePage -> DynamoDBGetSimilarUsersActivity: User
DynamoDBGetSimilarUsersActivity -> UsersTable: getSimilarUsers()
UsersTable -> DynamoDBGetSimilarUsersActivity: List<Users>
DynamoDBGetSimilarUsersActivity -> WebsiteHomePage: List<Users>
WebsiteHomePage -> Client: List<Users>
@enduml